version: '3.4'
services:
        php:
                image: php:8.0.30-apache
                build:
                       dockerfile: Dockerfile
                       context: . 
                ports:
                        - 80:80
                volumes:
                        - C:\Users\jcgut\Desktop\PHPDocker/src:/var/www/html
                links:
                        - mariadb
        mariadb:
                image: mariadb:10
                volumes:
                        - mariadb:/var/lib/mysql
                ports:
                        - 3306:3306
                environment:
                        TZ: "Europe/Madrid"
                        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
                        MYSQL_USER: "daw"
                        MYSQL_PASSWORD: "dawPassw0rd"
                        MYSQL_DATABASE: "ventas" 
        phpmyadmin:
                image: phpmyadmin
                ports:
                        - 8080:80
                environment:
                        - PMA_HOST=mariadb
                        - PMA_PORT:3306        
volumes:
        mariadb: